title: "[Feature request] "
labels: ["Submit a request for a new feature or improvement."]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is the request related to a problem?
      description: "Provide a clear and concise description of what the problem is. Ex. I'm frustrated when [...]"
  - type: textarea
    id: feature
    attributes:
      label: The feature you would like
      description: "Provide a clear and concise description of what you want to happen."
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Describe alternatives you've considered"
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
